//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC301.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ventas
    {
        public int IdVenta { get; set; }
        public Nullable<System.DateTime> FechaVenta { get; set; }
        public Nullable<int> ClaveP { get; set; }
        public Nullable<int> IdP { get; set; }
    
        public virtual productos productos { get; set; }
        public virtual proveedores proveedores { get; set; }
    }
}
